export const countries = [
  { "value": "AF", "name": "Afghanistan" },
  { "value": "ZA", "name": "Afrique du Sud" },
  { "value": "AL", "name": "Albanie" },
  { "value": "DZ", "name": "Algérie" },
  { "value": "DE", "name": "Allemagne" },
  { "value": "AD", "name": "Andorre" },
  { "value": "AO", "name": "Angola" },
  { "value": "AI", "name": "Anguilla" },
  { "value": "AQ", "name": "Antarctique" },
  { "value": "AG", "name": "Antigua-et-Barbuda" },
  { "value": "AN", "name": "Antilles néerlandaises" },
  { "value": "SA", "name": "Arabie saoudite" },
  { "value": "AR", "name": "Argentine" },
  { "value": "AM", "name": "Arménie" },
  { "value": "AW", "name": "Aruba" },
  { "value": "AU", "name": "Australie" },
  { "value": "AT", "name": "Autriche" },
  { "value": "AZ", "name": "Azerbaïdjan" },
  { "value": "BS", "name": "Bahamas" },
  { "value": "BH", "name": "Bahreïn" },
  { "value": "BD", "name": "Bangladesh" },
  { "value": "BB", "name": "Barbade" },
  { "value": "BY", "name": "Bélarus" },
  { "value": "BE", "name": "Belgique" },
  { "value": "BZ", "name": "Belize" },
  { "value": "BJ", "name": "Bénin" },
  { "value": "BM", "name": "Bermudes" },
  { "value": "BT", "name": "Bhoutan" },
  { "value": "BO", "name": "Bolivie" },
  { "value": "BA", "name": "Bosnie-Herzégovine" },
  { "value": "BW", "name": "Botswana" },
  { "value": "BR", "name": "Brésil" },
  { "value": "BN", "name": "Brunéi Darussalam" },
  { "value": "BG", "name": "Bulgarie" },
  { "value": "BF", "name": "Burkina Faso" },
  { "value": "BI", "name": "Burundi" },
  { "value": "KH", "name": "Cambodge" },
  { "value": "CM", "name": "Cameroun" },
  { "value": "CA", "name": "Canada" },
  { "value": "CV", "name": "Cap-Vert" },
  { "value": "EA", "name": "Ceuta et Melilla" },
  { "value": "CL", "name": "Chili" },
  { "value": "CN", "name": "Chine" },
  { "value": "CY", "name": "Chypre" },
  { "value": "CO", "name": "Colombie" },
  { "value": "KM", "name": "Comores" },
  { "value": "CG", "name": "Congo-Brazzaville" },
  { "value": "KP", "name": "Corée du Nord" },
  { "value": "KR", "name": "Corée du Sud" },
  { "value": "CR", "name": "Costa Rica" },
  { "value": "CI", "name": "Côte d’Ivoire" },
  { "value": "HR", "name": "Croatie" },
  { "value": "CU", "name": "Cuba" },
  { "value": "DK", "name": "Danemark" },
  { "value": "DG", "name": "Diego Garcia" },
  { "value": "DJ", "name": "Djibouti" },
  { "value": "DM", "name": "Dominique" },
  { "value": "EG", "name": "Égypte" },
  { "value": "SV", "name": "El Salvador" },
  { "value": "AE", "name": "Émirats arabes unis" },
  { "value": "EC", "name": "Équateur" },
  { "value": "ER", "name": "Érythrée" },
  { "value": "ES", "name": "Espagne" },
  { "value": "EE", "name": "Estonie" },
  { "value": "VA", "name": "État de la Cité du Vatican" },
  { "value": "FM", "name": "États fédérés de Micronésie" },
  { "value": "US", "name": "États-Unis" },
  { "value": "ET", "name": "Éthiopie" },
  { "value": "FJ", "name": "Fidji" },
  { "value": "FI", "name": "Finlande" },
  { "value": "FR", "name": "France" }
]
