export const departmentCI = [
  { name: "Abengourou", value: "abengourou", subPrefectures: ["Abengourou", "Amélékia", "Aniassué", "Ebilassokro", "Niablé", "Zaranou"] },
  { name: "Abidjan", value: "abidjan", subPrefectures: ["Anyama", "Bingerville", "Brofodoumé", "Songon"] },
  { name: "Aboisso", value: "aboisso", subPrefectures: ["Aboisso", "Adaou", "Ayamé", "Kouakro", "Maféré", "N'Gasso", "Tiapoum"] },
  { name: "Adiaké", value: "adiake", subPrefectures: ["Adiaké", "Assinie-Mafia", "Etueboué"] },
  { name: "Adzopé", value: "adzope", subPrefectures: ["Adzopé", "Agou", "Ananguié", "Annépé", "Assikoi", "Yakassé-Mé"] },
  { name: "Agboville", value: "agboville", subPrefectures: ["Agboville", "Aboudé", "Ananguié", "Céchi", "Grand-Morié", "Guessiguié", "Loviguié", "Oghlwapo", "Rubino"] },
  { name: "Agnibilékrou", value: "agnibilekrou", subPrefectures: ["Agnibilékrou", "Akoboissué", "Damé", "Duffrébo"] },
  { name: "Akoupé", value: "akoupe", subPrefectures: ["Akoupé", "Bécouéfin", "Bacon"] },
  { name: "Alépé", value: "alepe", subPrefectures: ["Alépé", "Aboisso-Comoé", "Danguira", "Oghlwapo"] },
  { name: "Arrah", value: "arrah", subPrefectures: ["Arrah", "Kouadiokro", "Krégbé"] },
  { name: "Attiégouakro", value: "attiegouakro", subPrefectures: ["Attiégouakro", "Lolomambo"] },
  { name: "Bangolo", value: "bangolo", subPrefectures: ["Bangolo", "Béoué-Zibiao", "Bléniméouin", "Diéouzon", "Gohouo-Zagna", "Guinglo-Tahouaké", "Zéo", "Zou"] },
  { name: "Bettié", value: "bettie", subPrefectures: ["Bettié", "Diamarakro"] },
  { name: "Biankouma", value: "biankouma", subPrefectures: ["Biankouma", "Blapleu", "Gbonné", "Gouiné", "Kpata", "Saba", "Santa"] },
  { name: "Bloléquin", value: "blolequin", subPrefectures: ["Bloléquin", "Diboké", "Goya-Zibiao", "Tinhou", "Zéaglo"] },
  { name: "Bocanda", value: "bocanda", subPrefectures: ["Bocanda", "Benganssou", "Kouadioblékro", "N'Gze-Cécé-Koffikro"] },
  { name: "Bondoukou", value: "bondoukou", subPrefectures: ["Bondoukou", "Appimadoum", "Bondo", "Gouméré", "Laoudi-Ba", "Pinda-Boroko", "Sapli-Sépingo", "Sorobango", "Tabagne", "Tagadi", "Taoudi", "Yezimala"] },
  { name: "Bongouanou", value: "bongouanou", subPrefectures: ["Bongouanou", "Andé", "Assié-Koumassi", "N'Guessankro"] },
  { name: "Botro", value: "botro", subPrefectures: ["Botro", "Diabo", "Krofoinsou", "Languibonou"] },
  { name: "Bouaflé", value: "bouafle", subPrefectures: ["Bouaflé", "Begbessou", "Bonon", "Kouétinfla", "N'Duffoukankro", "Pakouabo", "Tibéita"] },
  { name: "Bouaké", value: "bouake", subPrefectures: ["Bouaké-Ville", "Bouaké-SP", "Bounda", "Brobo", "Mamini", "N'Djébonouan"] },
  { name: "Bouna", value: "bouna", subPrefectures: ["Bouna", "Bouko", "Ondéfidouo", "Youndouo"] },
  { name: "Boundiali", value: "boundiali", subPrefectures: ["Boundiali", "Baya", "Ganaoni", "Gbon", "Kolia", "Kasséré", "Sianhala"] },
  { name: "Buyo", value: "buyo", subPrefectures: ["Buyo", "Dapéoua"] },
  { name: "Béoumi", value: "beoumi", subPrefectures: ["Béoumi", "Ando-Kékrénou", "Bodokro", "Kondrobo", "Lolobo", "Marabadiassa", "N'Guessankro"] },
  { name: "Dabakala", value: "dabakala", subPrefectures: ["Dabakala", "Bassawa", "Boniérédougou", "Foumbolo", "N'Golo-Kaha", "Sokala-Sobara", "Tendéné-Bambaras", "Tiembe"] },
  { name: "Dabou", value: "dabou", subPrefectures: ["Dabou", "Lopou", "Toupah"] },
  { name: "Daloa", value: "daloa", subPrefectures: ["Daloa", "Bédiala", "Gadago", "Gboguhé", "Gonaté", "Zaïbo"] },
  { name: "Danané", value: "danane", subPrefectures: ["Danané", "Daleu", "Mahapleu", "Seileu", "Zonneu"] },
  { name: "Daoukro", value: "daoukro", subPrefectures: ["Daoukro", "Ettrokro", "N'Gattakro", "Samazza"] },
  { name: "Didiévi", value: "didievi", subPrefectures: ["Didiévi", "Boli", "Molonou-Blé", "Raviart", "Thién'diékro"] },
  { name: "Dimbokro", value: "dimbokro", subPrefectures: ["Dimbokro", "Abigui", "Diangokro", "N'Guaibiékro"] },
  { name: "Divo", value: "divo", subPrefectures: ["Divo", "Chiépo", "Didoko", "Hiré", "Nébo", "Ogoudou"] },
  { name: "Djékanou", value: "djekanou", subPrefectures: ["Djékanou", "Bonikro"] },
  { name: "Doropo", value: "doropo", subPrefectures: ["Doropo", "Kalamon", "Niamoué"] },
  { name: "Duékoué", value: "duekoue", subPrefectures: ["Duékoué", "Bagohouo", "Gbapleu", "Guéhiébli"] },
  { name: "Ferkessédougou", value: "ferkessedougou", subPrefectures: ["Ferkessédougou", "Koumbala", "Togoniéré"] },
  { name: "Fresco", value: "fresco", subPrefectures: ["Fresco", "Gbagbam", "Dahiri"] },
  { name: "Gagnoa", value: "gagnoa", subPrefectures: ["Gagnoa", "Bayota", "Dahiépa-Kéhi", "Dignago", "Dougroupalégnoa", "Galébré", "Gnagbodougnoa", "Ouragahio", "Sérihio", "Yopohué"] },
  { name: "Gbéléban", value: "gbeleban", subPrefectures: ["Gbéléban", "Seydougou", "Tidji"] },
  { name: "Grand-Bassam", value: "grand-bassam", subPrefectures: ["Grand-Bassam", "Bongo", "Bonoua"] },
  { name: "Grand-Lahou", value: "grand-lahou", subPrefectures: ["Grand-Lahou", "Ahouanou", "Ebounou", "Toukouzou"] },
  { name: "Guiglo", value: "guiglo", subPrefectures: ["Guiglo", "Bédy-Goazon", "Kaade", "Nizahon"] },
  { name: "Guitry", value: "guitry", subPrefectures: ["Guitry", "Dairo-Didizo"] },
  { name: "Guéyo", value: "gueyo", subPrefectures: ["Guéyo", "Dabouyo"] },
  { name: "Issia", value: "issia", subPrefectures: ["Issia", "Bogguédia", "Iboguhé", "Namané", "Saïoua", "Nahio", "Tapeguia"] },
  { name: "Jacqueville", value: "jacqueville", subPrefectures: ["Jacqueville", "Attoutou", "Sikensi"] },
  { name: "Kani", "value": "kani", subPrefectures: ["Kani", "Djibrosso", "Fadiadougou", "Morondo"] },
  { name: "Kaniasso", value: "kaniasso", subPrefectures: ["Kaniasso", "Goulia", "Mahandiana-Sokourani"] },
  { name: "Katiola", value: "katiola", subPrefectures: ["Katiola", "Fronan", "Timbé"] },
  { name: "Kong", value: "kong", subPrefectures: ["Kong", "Bilimono", "Nafana", "Sikolo"] },
  { name: "Korhogo", value: "korhogo", subPrefectures: ["Korhogo", "Dassoungboho", "Karakoro", "Komborodougou", "M'Bengué", "Nafio", "Napiéolédougou", "Niofoin", "Siraniki", "Soia", "Tioroniaradougou"] },
  { name: "Koro", value: "koro", subPrefectures: ["Koro", "Booko", "Borotou", "Mahandougou", "Niokosso"] },
  { name: "Kouassi-Kouassikro", value: "kouassi-kouassikro", subPrefectures: ["Kouassi-Kouassikro", "Oussou"] },
  { name: "Kouibly", value: "kouibly", subPrefectures: ["Kouibly", "Nidrou", "Ouyably-Gnandrou", "Totrodrou"] },
  { name: "Koun-Fao", value: "koun-fao", subPrefectures: ["Koun-Fao", "Abokroman", "Boahia", "Kokomian", "Kouassi-Datékro"] },
  { name: "Kounahiri", value: "kounahiri", subPrefectures: ["Kounahiri", "Kongasso"] },
  { name: "Kouto", value: "kouto", subPrefectures: ["Kouto", "Blességué", "Gbon", "Kolia", "Sianhala"] },
  { name: "Lakota", value: "lakota", subPrefectures: ["Lakota", "Djidji", "Goudouko", "Niambézaria", "Zikisso"] },
  { name: "M'Bahiakro", value: "mbahiakro", subPrefectures: ["M'Bahiakro", "Bonguéra", "Kondossou"] },
  { name: "M'Batto", value: "mbatto", subPrefectures: ["M'Batto", "Assahara"] },
  { name: "Madinani", value: "madinani", subPrefectures: ["Madinani", "Fengolo", "N'Goltinvogo"] },
  { name: "Man", value: "man", subPrefectures: ["Man", "Bogouiné", "Fagnampleu", "Gbangbégouiné-Yati", "Logoualé", "Podiagouiné", "Sangouiné"] },
  { name: "Mankono", value: "mankono", subPrefectures: ["Mankono", "Bouandougou", "Marandallah", "Sarhala", "Tiéningboué"] },
  { name: "Minignan", value: "minignan", subPrefectures: ["Minignan", "Kaniasso", "Sokoro", "Tienko"] },
  { name: "Nassian", value: "nassian", subPrefectures: ["Nassian", "Bogofa", "Koutouba", "Sominassé"] },
  { name: "Niakaramandougou", value: "niakaramandougou", subPrefectures: ["Niakaramandougou", "Arikokaha", "Badikaha", "Niédiékaha", "Tafiré"] },
  { name: "Odienné", value: "odienne", subPrefectures: ["Odienné", "Bako", "Bougousso", "Dioulatiédougou", "Tiémé"] },
  { name: "Oumé", value: "oume", subPrefectures: ["Oumé", "Diégonéfla", "Guepahouo", "Tonla"] },
  { name: "Prikro", value: "prikro", subPrefectures: ["Prikro", "Anianou", "Famine", "Koffi-Amonkro", "N'Gattakro"] },
  { name: "Sakassou", value: "sakassou", subPrefectures: ["Sakassou", "Ayamé", "Dibri-Assirikro", "Toumodi-Sakassou"] },
  { name: "Samatiguila", value: "samatiguila", subPrefectures: ["Samatiguila", "Kimbirila-Sud"] },
  { name: "San-Pédro", value: "san-pedro", subPrefectures: ["San-Pédro", "Dago-Gabogui", "Dogbo", "Gabiadji", "Grand-Béréby"] },
  { name: "Sandégué", value: "sandegue", subPrefectures: ["Sandégué", "Dimandougou", "Yorobodi"] },
  { name: "Sassandra", value: "sassandra", subPrefectures: ["Sassandra", "Dakpadou", "Grihiri", "Lobo", "Medon", "Sago"] },
  { name: "Sikensi", value: "sikensi", subPrefectures: ["Sikensi", "Gomon"] },
  { name: "Sinfra", value: "sinfra", subPrefectures: ["Sinfra", "Bazré", "Kononfla"] },
  { name: "Sipilou", value: "sipilou", subPrefectures: ["Sipilou", "Yorodougou"] },
  { name: "Soubré", value: "soubre", subPrefectures: ["Soubré", "Grand-Zattry", "Liliyo", "Okrouyo"] },
  { name: "Séguéla", value: "seguela", subPrefectures: ["Séguéla", "Bobi", "Diarana", "Dualla", "Massala", "Sifié", "Worofla"] },
  { name: "Tabou", value: "tabou", subPrefectures: ["Tabou", "Djamandioké", "Grabo", "Olodio"] },
  { name: "Tanda", value: "tanda", subPrefectures: ["Tanda", "Amanvi", "Diamba", "Bakoutié-Yao-Fiéni", "Tiédjo"] },
  { name: "Taï", value: "tai", subPrefectures: ["Taï", "Zagné"] },
  { name: "Tengréla", value: "tengrela", subPrefectures: ["Tengréla", "Kanakono", "Papara"] },
  { name: "Tiapoum", value: "tiapoum", subPrefectures: ["Tiapoum", "Nouamou"] },
  { name: "Tiassalé", value: "tiassale", subPrefectures: ["Tiassalé", "Gbolouville", "Morokro", "N'douci"] },
  { name: "Tiébissou", value: "tiebisso", subPrefectures: ["Tiébissou", "Lomokro", "Molonou", "Yakpabo-Sakassou"] },
  { name: "Touba", value: "touba", subPrefectures: ["Touba", "Dioman", "Foungbesso", "Guintéguéla", "Koonan"] },
  { name: "Toulepleu", value: "toulepleu", subPrefectures: ["Toulepleu", "Bakoubli", "Méo", "Nézoa", "Péhé", "Tiobli"] },
  { name: "Toumodi", value: "toumodi", subPrefectures: ["Toumodi", "Angoda", "Boli", "Djekanou"] },
  { name: "Transua", value: "transua", subPrefectures: ["Transua", "Assuéfry", "Kouassi-Niaguini"] },
  { name: "Téhini", value: "tehini", subPrefectures: ["Téhini", "Gogo", "Tougbô"] },
  { name: "Vavoua", value: "vavoua", subPrefectures: ["Vavoua", "Bazra-Kattis", "Danon", "Séitifla"] },
  { name: "Yamoussoukro", value: "yamoussoukro", subPrefectures: ["Yamoussoukro", "Kossou"] },
  { name: "Zouan-Hounien", value: "zouan-hounien", subPrefectures: ["Zouan-Hounien", "Banneu", "Bin-Houyé", "Goulaleu", "Teapleu"] },
  { name: "Zuenoula", value: "zuenoula", subPrefectures: ["Zuenoula", "Gohitafla", "Iriéfla"] }
];
